version: 2
sources:
- name: internal_tech_kpi_bronze
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: backlog_asana_tasks
  - name: backlog_asana_projects
  - name: backlog_asana_sections
  - name: backlog_asana_teams
  - name: backlog_asana_tasks_custom_fields_enum_value
  - name: backlog_asana_tasks_custom_fields
