version: 2
sources:
- name: test_normalization
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_branches
  - name: _airbyte_raw_jobs
  - name: _airbyte_raw_organizations
  - name: _airbyte_raw_pull_request_stats
  - name: _airbyte_raw_pull_requests
  - name: _airbyte_raw_repositories
  - name: _airbyte_raw_users
  - name: _airbyte_raw_workflow_runs
  - name: _airbyte_raw_workflows
